### ISSUE TITLE
Pouvoir-1.5.0 不兼容spigot 安装后无法进入服务器

### ISSUE THREAD

**Issue by luoxiawuchen** [Glom-c/Pouvoir#2]
服务端类型：spigot
版本：1.16.5

错误描述：
1、插件正常载入（无报错）
![image](https://user-images.githubusercontent.com/64759847/190062281-227ea180-b7d4-4205-ad62-f15980b34c87.png)

2、服务端已开启，但多人列表获取不到服务器信号
![image](https://user-images.githubusercontent.com/64759847/190062411-e683a2cd-4095-4a06-8675-27d9d4ad0165.png)

3、进入服务器提示 Failed to verify username （如果是开启正版验证会提示，认证服务器宕机）

4、后台错误信息
[12:52:05] [User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@70d8cb50[id=196fba29-6dd5-3d88-91bf-22433da325d3,name=test,properties={},legacy=false] (/192.168.2.102:10522): Failed to verify username!
[12:52:05] [User Authenticator #1/WARN]: Exception verifying test
java.lang.IllegalStateException: AsyncPlayerPreLoginEvent cannot be triggered asynchronously from primary server thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:568) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:299) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.LoginListener$1.run(LoginListener.java:203) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
[12:52:05] [Server thread/INFO]: com.mojang.authlib.GameProfile@70d8cb50[id=196fba29-6dd5-3d88-91bf-22433da325d3,name=test,properties={},legacy=false] (/192.168.2.102:10522) lost connection: Failed to verify username!

5、相同测试环境下 paper不存在此问题（jdk16、PlaceholderAPI-2.10.9、Pouvoir-1.5.0）

**Comment by Glom-c** [comment]
已修复
