### ISSUE TITLE
Pouvoir-1.6.0-A-72版本，purpur报错

### ISSUE THREAD

**Issue by Q2297045667** [Glom-c/Pouvoir#5]
Pouvoir版本：1.6.0-A-71
服务端版本：purpur-1.19.3-1902

[23:56:15] [Server thread/INFO]: [Pouvoir] Pouĺ ä˝çŹŚ pou ćł¨ĺćĺ! ćĽčŞ: Pouvoir 1.6.0-dev-72 By: [Glom_]
[23:56:16] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/skillw/pouvoir/api/map/LowerKeyMap
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[23:56:16] [Server thread/WARN]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[23:56:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:226)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[23:56:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:131)
[23:56:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.Class.privateGetPublicFields(Class.java:3324)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.Class.getFields(Class.java:1928)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.internal.core.plugin.PouManagerUtils.initPouManagers$Pouvoir(PouManagerUtils.kt:20)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.internal.core.plugin.SubPouvoirHandler.inject(SubPouvoirHandler.kt:12)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager$loadSubPou$4$1.invoke(TotalManager.kt:62)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager$loadSubPou$4$1.invoke(TotalManager.kt:62)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.util.RunKt.safe(Run.kt:17)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager.loadSubPou(TotalManager.kt:62)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager.access$loadSubPou(TotalManager.kt:23)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager$load$2$1.invoke(TotalManager.kt:33)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager$load$2$1.invoke(TotalManager.kt:33)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.util.RunKt.safe(Run.kt:17)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.api.plugin.TotalManager.load(TotalManager.kt:33)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:131)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:101)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:60)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:197)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[23:56:16] [Server thread/WARN]: 	at Pouvoir-1.6.0-dev-72.jar//com.skillw.pouvoir.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:87)
[23:56:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:494)
[23:56:16] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[23:56:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[23:56:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:56:16] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.skillw.pouvoir.api.map.LowerKeyMap
[23:56:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179)
[23:56:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126)
[23:56:16] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[23:56:16] [Server thread/WARN]: 	... 37 more

**Comment by Glom-c** [comment]
与新版Pouvoir配套的附属还没有发布，请等待配套附属发布再更新
